"""initiate

Revision ID: 121562881b10
Revises:
Create Date: 2026-03-05 13:13:29.190625

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "121562881b10"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("extension", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("original", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("media_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("size_mb", sa.Float(), nullable=True),
        sa.Column("thumbnail", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "roles",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "users",
        sa.Column(
            "unverified_phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False
        ),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cnic", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("image", sa.JSON(), nullable=True),
        sa.Column(
            "status", sa.Enum("active", "disabled", name="userstatus"), nullable=False
        ),
        sa.Column("is_root", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("country_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("currency_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "currency_symbol", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("otp_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("otp_expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_full_name"), "users", ["full_name"], unique=False)
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=False)
    op.create_index(
        "uq_users_phone_verified",
        "users",
        ["phone"],
        unique=True,
        postgresql_where=sa.text("verified = true"),
    )
    op.create_index(
        "uq_users_verified_email",
        "users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("email_verified = true"),
    )
    op.create_table(
        "default_ride_settings",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("car_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("car_pic", sa.JSON(), nullable=True),
        sa.Column("seats_available", sa.Integer(), nullable=False),
        sa.Column("price_per_seat", sa.Float(), nullable=True),
        sa.Column("total_price", sa.Float(), nullable=True),
        sa.Column("negotiable", sa.Boolean(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "car_type",
            sa.Enum(
                "sedan",
                "hatchback",
                "suv",
                "crossover",
                "coupe",
                "convertible",
                "pickup",
                "van",
                "wagon",
                "minivan",
                "jeep",
                "other",
                name="cartype",
            ),
            nullable=True,
        ),
        sa.Column("car_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("car_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "reviews",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reviewer_id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reviewer_id", "target_id", name="uq_reviewer_target"),
    )
    op.create_table(
        "rides",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("from_location", sa.JSON(), nullable=True),
        sa.Column("to_location", sa.JSON(), nullable=True),
        sa.Column("from_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("to_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("arrival_time", sa.DateTime(), nullable=False),
        sa.Column("car_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("car_pic", sa.JSON(), nullable=True),
        sa.Column("other_images", sa.JSON(), nullable=True),
        sa.Column("seats_available", sa.Integer(), nullable=False),
        sa.Column("price_per_seat", sa.Float(), nullable=True),
        sa.Column("total_price", sa.Float(), nullable=True),
        sa.Column("negotiable", sa.Boolean(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "car_type",
            sa.Enum(
                "sedan",
                "hatchback",
                "suv",
                "crossover",
                "coupe",
                "convertible",
                "pickup",
                "van",
                "wagon",
                "minivan",
                "jeep",
                "other",
                name="cartype",
            ),
            nullable=False,
        ),
        sa.Column("car_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("car_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rides_from_address"), "rides", ["from_address"], unique=False
    )
    op.create_index(op.f("ix_rides_to_address"), "rides", ["to_address"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rides_to_address"), table_name="rides")
    op.drop_index(op.f("ix_rides_from_address"), table_name="rides")
    op.drop_table("rides")
    op.drop_table("reviews")
    op.drop_table("default_ride_settings")
    op.drop_index(
        "uq_users_verified_email",
        table_name="users",
        postgresql_where=sa.text("email_verified = true"),
    )
    op.drop_index(
        "uq_users_phone_verified",
        table_name="users",
        postgresql_where=sa.text("verified = true"),
    )
    op.drop_index(op.f("ix_users_phone"), table_name="users")
    op.drop_index(op.f("ix_users_full_name"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("media")
    # ### end Alembic commands ###
