"""email updating

Revision ID: 34a2dc7a16f8
Revises: 6612e8869fe8
Create Date: 2026-01-05 12:59:36.033282

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "34a2dc7a16f8"
down_revision: Union[str, Sequence[str], None] = "6612e8869fe8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(
        "uq_users_verified_email",
        "users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("email_verified = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_users_verified_email",
        table_name="users",
        postgresql_where=sa.text("email_verified = true"),
    )
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)

    # ### end Alembic commands ###
