"""default ride setting

Revision ID: 3ea31eab6a98
Revises: 952427bf4422
Create Date: 2025-12-17 11:43:09.106734

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "3ea31eab6a98"
down_revision: Union[str, Sequence[str], None] = "952427bf4422"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "default_ride_settings",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("car_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("car_pic", sa.JSON(), nullable=True),
        sa.Column("seats_available", sa.Integer(), nullable=False),
        sa.Column("price_per_seat", sa.Float(), nullable=True),
        sa.Column("total_price", sa.Float(), nullable=True),
        sa.Column("negotiable", sa.Boolean(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "car_type",
            sa.Enum(
                "sedan",
                "hatchback",
                "suv",
                "crossover",
                "coupe",
                "convertible",
                "pickup",
                "van",
                "wagon",
                "minivan",
                "jeep",
                "other",
                name="cartype",
                create_type=False,
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("car_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("car_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("default_ride_settings")
    # ### end Alembic commands ###
