"""image replace with file_url

Revision ID: 6237e965ac99
Revises: eda59e889be2
Create Date: 2025-12-08 12:17:21.652766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6237e965ac99'
down_revision: Union[str, Sequence[str], None] = 'eda59e889be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image', sa.JSON(), nullable=True))
    op.drop_column('users', 'photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'image')
    # ### end Alembic commands ###
