"""user should unique

Revision ID: 77e91a9cc18a
Revises: 3ea31eab6a98
Create Date: 2025-12-18 11:42:59.203296

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "77e91a9cc18a"
down_revision: Union[str, Sequence[str], None] = "3ea31eab6a98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_unique_constraint(None, "default_ride_settings", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "default_ride_settings", type_="unique")

    # ### end Alembic commands ###
