"""otp added

Revision ID: 905c8a151a4d
Revises: 95c1c472b5be
Create Date: 2026-01-20 15:11:53.717995

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "905c8a151a4d"
down_revision: Union[str, Sequence[str], None] = "95c1c472b5be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("otp_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column("users", sa.Column("otp_expires_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "otp_expires_at")
    op.drop_column("users", "otp_code")
    # ### end Alembic commands ###
