"""auto

Revision ID: 95c1c472b5be
Revises: 34a2dc7a16f8
Create Date: 2026-01-20 11:10:08.956455

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "95c1c472b5be"
down_revision: Union[str, Sequence[str], None] = "34a2dc7a16f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "default_ride_settings",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("car_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("car_pic", sa.JSON(), nullable=True),
        sa.Column("seats_available", sa.Integer(), nullable=False),
        sa.Column("price_per_seat", sa.Float(), nullable=True),
        sa.Column("total_price", sa.Float(), nullable=True),
        sa.Column("negotiable", sa.Boolean(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "car_type",
            sa.Enum(
                "sedan",
                "hatchback",
                "suv",
                "crossover",
                "coupe",
                "convertible",
                "pickup",
                "van",
                "wagon",
                "minivan",
                "jeep",
                "other",
                name="cartype",
                create_type=False,  # ✅ IMPORTANT
            ),
            nullable=True,
        ),
        sa.Column("car_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("car_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "reviews",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reviewer_id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reviewer_id", "target_id", name="uq_reviewer_target"),
    )
    op.create_table(
        "rides",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("from_location", sa.JSON(), nullable=True),
        sa.Column("to_location", sa.JSON(), nullable=True),
        sa.Column("from_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("to_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("arrival_time", sa.DateTime(), nullable=False),
        sa.Column("car_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("car_pic", sa.JSON(), nullable=True),
        sa.Column("other_images", sa.JSON(), nullable=True),
        sa.Column("seats_available", sa.Integer(), nullable=False),
        sa.Column("price_per_seat", sa.Float(), nullable=True),
        sa.Column("total_price", sa.Float(), nullable=True),
        sa.Column("negotiable", sa.Boolean(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "car_type",
            sa.Enum(
                "sedan",
                "hatchback",
                "suv",
                "crossover",
                "coupe",
                "convertible",
                "pickup",
                "van",
                "wagon",
                "minivan",
                "jeep",
                "other",
                name="cartype",
                create_type=False,  # ✅ IMPORTANT
            ),
            nullable=False,
        ),
        sa.Column("car_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("car_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rides_from_address"), "rides", ["from_address"], unique=False
    )
    op.create_index(op.f("ix_rides_to_address"), "rides", ["to_address"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rides_to_address"), table_name="rides")
    op.drop_index(op.f("ix_rides_from_address"), table_name="rides")
    op.drop_table("rides")
    op.drop_table("reviews")
    op.drop_table("default_ride_settings")
    # ### end Alembic commands ###
