"""created_at media

Revision ID: eda59e889be2
Revises: 6802a57419d1
Create Date: 2025-12-05 16:53:07.173707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda59e889be2'
down_revision: Union[str, Sequence[str], None] = '6802a57419d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('media', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'updated_at')
    op.drop_column('media', 'created_at')
    # ### end Alembic commands ###
