"""user_phone

Revision ID: a5691fa71ccc
Revises: 0d1cf1c9daad
Create Date: 2025-12-01 14:26:44.121409

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a5691fa71ccc"
down_revision: Union[str, Sequence[str], None] = "0d1cf1c9daad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "unverified_phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.alter_column("users", "phone", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_index(
        op.f("uq_users_phone_verified_true"),
        table_name="users",
        postgresql_where="(verified = true)",
    )
    op.create_index(
        "uq_users_phone_verified",
        "users",
        ["phone"],
        unique=True,
        postgresql_where=sa.text("verified = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_users_phone_verified",
        table_name="users",
        postgresql_where=sa.text("verified = true"),
    )
    op.create_index(
        op.f("uq_users_phone_verified_true"),
        "users",
        ["phone"],
        unique=True,
        postgresql_where="(verified = true)",
    )
    op.alter_column("users", "phone", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("users", "unverified_phone")
    # ### end Alembic commands ###
